{% set version = "2.0.9" %}

package:
  name: bob.blitz
  version: {{ version }}

source:
  fn: bob.blitz-{{ version }}.zip
  url: https://pypi.io/packages/source/b/bob.blitz/bob.blitz-{{ version }}.zip
  md5: 3818dfa73f9b78daba9b0468e878f7c0

build:
  number: 1
  skip: true  # [win]

requirements:
  build:
  - python
  - setuptools
  - bob.extension
  - numpy x.x
  - pkg-config
  - libblitz 0.10|0.10.*
  - boost 1.61.*
  - cmake

  run:
  - python
  - bob.extension
  - numpy x.x
  - libblitz 0.10|0.10.*
  - boost 1.61.*

test:
  requires:
  - nose

  imports:
  - bob
  - bob.blitz

  commands:
  - nosetests -sv bob.blitz

about:
  home: http://github.com/bioidiap/bob.blitz
  license: Modified BSD License (3-clause)
  summary: Bindings for Blitz++ (a C++ array template library)

extra:
  recipe-maintainers:
  - 183amir
